/* Complete ISO 3166-1 alpha-2 country list */
const COUNTRIES = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AG", name: "Antigua e Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaigian" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Bielorussia" },
  { code: "BE", name: "Belgio" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia ed Erzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brasile" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" },
  { code: "KH", name: "Cambogia" },
  { code: "CM", name: "Camerun" },
  { code: "CA", name: "Canada" },
  { code: "CF", name: "Repubblica Centrafricana" },
  { code: "TD", name: "Ciad" },
  { code: "CL", name: "Cile" },
  { code: "CN", name: "Cina" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comore" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo (RDC)" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Costa d'Avorio" },
  { code: "HR", name: "Croazia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cipro" },
  { code: "CZ", name: "Repubblica Ceca" },
  { code: "DK", name: "Danimarca" },
  { code: "DJ", name: "Gibuti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Repubblica Dominicana" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egitto" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Guinea Equatoriale" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Etiopia" },
  { code: "FJ", name: "Figi" },
  { code: "FI", name: "Finlandia" },
  { code: "FR", name: "Francia" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germania" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Grecia" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Ungheria" },
  { code: "IS", name: "Islanda" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Irlanda" },
  { code: "IL", name: "Israele" },
  { code: "IT", name: "Italia" },
  { code: "JM", name: "Giamaica" },
  { code: "JP", name: "Giappone" },
  { code: "JO", name: "Giordania" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KP", name: "Corea del Nord" },
  { code: "KR", name: "Corea del Sud" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kirghizistan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Lettonia" },
  { code: "LB", name: "Libano" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libia" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lituania" },
  { code: "LU", name: "Lussemburgo" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldive" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Isole Marshall" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Messico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Marocco" },
  { code: "MZ", name: "Mozambico" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Paesi Bassi" },
  { code: "NZ", name: "Nuova Zelanda" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "MK", name: "Macedonia del Nord" },
  { code: "NO", name: "Norvegia" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestina" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua Nuova Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Perù" },
  { code: "PH", name: "Filippine" },
  { code: "PL", name: "Polonia" },
  { code: "PT", name: "Portogallo" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Ruanda" },
  { code: "KN", name: "Saint Kitts e Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent e Grenadine" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "São Tomé e Príncipe" },
  { code: "SA", name: "Arabia Saudita" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovacchia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Isole Salomone" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "Sudafrica" },
  { code: "SS", name: "Sudan del Sud" },
  { code: "ES", name: "Spagna" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Svezia" },
  { code: "CH", name: "Svizzera" },
  { code: "SY", name: "Siria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tagikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailandia" },
  { code: "TL", name: "Timor Est" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad e Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turchia" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ucraina" },
  { code: "AE", name: "Emirati Arabi Uniti" },
  { code: "GB", name: "Regno Unito" },
  { code: "US", name: "Stati Uniti" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" }
].sort((a, b) => a.name.localeCompare(b.name, 'it'));

/* Build a fast lookup map */
const COUNTRY_MAP = Object.fromEntries(COUNTRIES.map(c => [c.code, c.name]));
